In [3]:
import numpy as np
import pandas as pd

In [5]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [8]:
#1.Using numpy functions, multiply the following arrays using matrix multiplication.
 #a=np.arange(4).reshape(2,2)
# b=np.arange(6).reshape(3,2)
a=np.arange(4).reshape(2,2)
b=np.arange(6).reshape(3,2)
b_trps=np.transpose(b)
print(a)
print(b_trps)
c=a @ b_trps
print(c)

[[0 1]
 [2 3]]
[[0 2 4]
 [1 3 5]]
[[ 1  3  5]
 [ 3 13 23]]


In [21]:
OrganD_df=pd.read_excel('OrganDonor_Consolidated.xlsx')


In [26]:
OrganD_df

PatientID   age gender      race              causeofdeath  \
0       OPO1_P155959  54.0      M     White                   Unknown   
1       OPO1_P297347  78.0      M  Hispanic                   Unknown   
2       OPO1_P399316  57.0      M  Hispanic                    Anoxia   
3       OPO1_P246407  78.0      F     Black  cerebrovascular accident   
4       OPO1_P187209  70.0      F     White                   Unknown   
...              ...   ...    ...       ...                       ...   
133096   OPO6_P54946  54.0      F     Black                    Anoxia   
133097  OPO6_P630991  63.0      M     Black  cerebrovascular accident   
133098    OPO6_P8748  28.0      M     White                    Anoxia   
133099    OPO6_P5461  85.0      F     White                    Anoxia   
133100  OPO6_P942291  32.0      M     Black                     Other   

       mechanism_of_death  brain_death       time_asystole time_brain_death  
0                 Unknown            0 2036-01-02 18:26:00              NaT  
1                 Unknown            0 2031-12-24 14:06:00              NaT  
2                 Unknown            0 2034-05-11 00:00:00              NaT  
3                  Stroke            0 2035-06-14 14:18:00              NaT  
4                 Unknown            0 2034-02-18 18:50:00              NaT  
...                   ...          ...                 ...              ...  
133096     Natural Causes            0 2032-09-16 02:34:00              NaT  
133097             Stroke            0 2034-06-06 22:14:00              NaT  
133098  Drug Intoxication            0                 NaT              NaT  
133099     Cardiovascular            0                 NaT              NaT  
133100     Natural Causes            0                 NaT              NaT  

[133101 rows x 9 columns]

In [22]:
DataD_df=pd.read_excel('DataDictionary.xlsx')

In [32]:
DataD_df

Field                                        Description  \
0                    OPO                                  Anonymized OPO ID   
1              PatientID                              Anonymized Patient ID   
2             HospitalID                 Referring hospital (anonymized ID)   
3                    Age                                  Exact patient age   
4                 Gender                                 Patient sex/gender   
5                   Race                                 Patient sex/gender   
6        Tissue_Referral     Was patient also referred for tissue donation?   
7           Eye_Referral     Was patient also referred for cornea donation?   
8           causeofdeath                                     Cause of death   
9     mechanism_of_death                    UNOS defined mechanism of death   
10           brain_death                   Was patient declared brain dead?   
11  Approached Relatives  Was patient's next-of-kin approached for donat...   
12  Authorized By Family  Did patient or their next-of-kin consent to do...   
13         Cross_Clamped   Was patient cross-clamped for organ procurement?   
14          transplanted        Did patients organ(s) lead to a transplant?   
15      time_brain_death                                Time of brain death   
16         time_asystole              Time of asystole (i.e. cardiac death)   
17         time_referred                     Time of referral from hospital   
18       time_approached                            Time of approach by OPO   
19       time_authorized  Time of consent given for donation by patient ...   
20         time_procured          Time of cross clamp for organ procurement   
21         Referral_Year                 Year in which patient was referred   
22    Referral_DayofWeek          Day of week on which patient was referred   
23         Procured_Year  Year in which patient was cross-clamped for pr...   
24         outcome_heart  Final disposition of procured heart (Transplan...   
25         outcome_liver  Final disposition of procured liver (Transplan...   
26   outcome_kidney_left  Final disposition of procured left kidney (Tra...   
27  outcome_kidney_right  Final disposition of procured right kidney (Tr...   
28     outcome_lung_left  Final disposition of procured left lung (Trans...   
29    outcome_lung_right  Final disposition of procured right lung (Tran...   
30     outcome_intestine  Final disposition of procured intestine (Trans...   
31      outcome_pancreas  Final disposition of procured pancreas (Transp...   

        Type                                              Notes  
0     String                                          e.g. OPO5  
1     String                               "e.g. ""OPO5_P123"""  
2     String                                "e.g. ""OPO5_H12"""  
3    Integer  If exact patient age was over 89, the age is l...  
4     String                                             M or F  
5     String  Five categories (Black/Af-Am, White/Caucasian,...  
6    Boolean  1- referred for tissue donation\n0-not referre...  
7    Boolean  1- referred for eye donation\n0-not referred f...  
8     String                               Categorical variable  
9     String     Categorical variable based on UNOS definitions  
10   Boolean  Brain death may not be documented if the OPO r...  
11   Boolean  0-patient's next-of-kin not approached for don...  
12   Boolean  1-patient or their next-of-kin consent to dona...  
13   Boolean  1 patient cross-clamped for organ procurement\...  
14   Boolean  1-patients organ(s) transplanted\n0- patients ...  
15  Datetime  Randomly date-shifted (all timestamps from the...  
16  Datetime  Randomly date-shifted (all timestamps from the...  
17  Datetime  Randomly date-shifted (all timestamps from the...  
18  Datetime  Randomly date-shifted (all timestamps from the...  
19  Datetime  Randomly date-shifted (all timestamps from the...  
20  Datetime  Randomly da

In [61]:
#2.On Average, what is the time that passes between approach and procurement?
sub_OrganD_df=OrganD_df[['time_approached','time_procured']]


KeyError: "None of [Index(['time_approached', 'time_procured'], dtype='object')] are in the [columns]"

In [9]:
df_donor_details=pd.read_excel('OrganDonor_Consolidated.xlsx',sheet_name='DonorDetails')
df_donor_details

PatientID   age gender      race              causeofdeath  \
0       OPO1_P155959  54.0      M     White                   Unknown   
1       OPO1_P297347  78.0      M  Hispanic                   Unknown   
2       OPO1_P399316  57.0      M  Hispanic                    Anoxia   
3       OPO1_P246407  78.0      F     Black  cerebrovascular accident   
4       OPO1_P187209  70.0      F     White                   Unknown   
...              ...   ...    ...       ...                       ...   
133096   OPO6_P54946  54.0      F     Black                    Anoxia   
133097  OPO6_P630991  63.0      M     Black  cerebrovascular accident   
133098    OPO6_P8748  28.0      M     White                    Anoxia   
133099    OPO6_P5461  85.0      F     White                    Anoxia   
133100  OPO6_P942291  32.0      M     Black                     Other   

       mechanism_of_death  brain_death       time_asystole time_brain_death  
0                 Unknown            0 2036-01-02 18:26:00              NaT  
1                 Unknown            0 2031-12-24 14:06:00              NaT  
2                 Unknown            0 2034-05-11 00:00:00              NaT  
3                  Stroke            0 2035-06-14 14:18:00              NaT  
4                 Unknown            0 2034-02-18 18:50:00              NaT  
...                   ...          ...                 ...              ...  
133096     Natural Causes            0 2032-09-16 02:34:00              NaT  
133097             Stroke            0 2034-06-06 22:14:00              NaT  
133098  Drug Intoxication            0                 NaT              NaT  
133099     Cardiovascular            0                 NaT              NaT  
133100     Natural Causes            0                 NaT              NaT  

[133101 rows x 9 columns]

In [19]:
#7.Make Patient ID as index to the table.


subdf_donor_details=df_donor_details['PatientID']
column_name=['age','gender','race','causeofdeath','mechanism_of_death','brain_death','time_asystole','time_brain_death']
subdf_donor_details
s1=pd.DataFrame(data=df_donor_details,index=subdf_donor_details,columns=column_name)
s1

age gender race causeofdeath mechanism_of_death  brain_death  \
PatientID                                                                    
OPO1_P155959  NaN    NaN  NaN          NaN                NaN          NaN   
OPO1_P297347  NaN    NaN  NaN          NaN                NaN          NaN   
OPO1_P399316  NaN    NaN  NaN          NaN                NaN          NaN   
OPO1_P246407  NaN    NaN  NaN          NaN                NaN          NaN   
OPO1_P187209  NaN    NaN  NaN          NaN                NaN          NaN   
...           ...    ...  ...          ...                ...          ...   
OPO6_P54946   NaN    NaN  NaN          NaN                NaN          NaN   
OPO6_P630991  NaN    NaN  NaN          NaN                NaN          NaN   
OPO6_P8748    NaN    NaN  NaN          NaN                NaN          NaN   
OPO6_P5461    NaN    NaN  NaN          NaN                NaN          NaN   
OPO6_P942291  NaN    NaN  NaN          NaN                NaN          NaN   

             time_asystole time_brain_death  
PatientID                                    
OPO1_P155959           NaT              NaT  
OPO1_P297347           NaT              NaT  
OPO1_P399316           NaT              NaT  
OPO1_P246407           NaT              NaT  
OPO1_P187209           NaT              NaT  
...                    ...              ...  
OPO6_P54946            NaT              NaT  
OPO6_P630991           NaT              NaT  
OPO6_P8748             NaT              NaT  
OPO6_P5461             NaT              NaT  
OPO6_P942291           NaT              NaT  

[133101 rows x 8 columns]

In [51]:
#8.Create a dictionary with the Age and Cause of Death for any 5 random donors.
 #Access any one cause of death using the donors age using the get() function
dic={
    "PatientID":['OPO1_P155959','OPO1_P297347','OPO1_P399316','OPO1_P246407','OPO1_P187209'],
    "age":[54,78,57,78,70],
    "causeofdeath":['Unknown','Unknown','Anoxia','cerebrovascular accident','Unknown']
}
print(dic)


{'PatientID': ['OPO1_P155959', 'OPO1_P297347', 'OPO1_P399316', 'OPO1_P246407', 'OPO1_P187209'], 'age': [54, 78, 57, 78, 70], 'causeofdeath': ['Unknown', 'Unknown', 'Anoxia', 'cerebrovascular accident', 'Unknown']}


In [59]:
#8.Access any one cause of death using the donors age using the get() function

age=dic['age']
causeofdeath=dic['causeofdeath']
data=dict(zip(age,causeofdeath))
#data
print(data.get(78))

cerebrovascular accident


In [5]:
#Qu 16 -- How many donors were registered in each Organ Procurement Organization?
import pandas as pd
opo_hospdetails = pd.read_excel('OrganDonor_Consolidated.xlsx', sheet_name='OPO_HospDetails')
# Initialize an empty dictionary to store the donor counts for each OPO ID
opo_donor_count = {}
# Loop through the list of donor OPO IDs 
for opo in opo_hospdetails['OPO']:
    if opo in opo_donor_count:
        opo_donor_count[opo] += 1
    else:
        opo_donor_count[opo] = 1

# Display the count of donors for each OPO ID
for opo, count in opo_donor_count.items():
    print(f"{opo}: {count} donors")

OPO1: 32148 donors
OPO2: 16145 donors
OPO3: 12514 donors
OPO4: 33641 donors
OPO5: 15738 donors
OPO6: 22915 donors


In [10]:
#17 Calculate the average time between referral and procurement for each mechanism of death

import pandas as pd

df_donardetails = pd.read_excel('OrganDonor_Consolidated.xlsx')
dataframe_referraldetails = pd.read_excel('OrganDonor_Consolidated.xlsx', sheet_name='ReferralDetails')

# Merge df_donardetails and dataframe_referraldetails  
merged_data = pd.merge(dataframe_donardetails, dataframe_referraldetails, on='PatientID', how='inner')

# Calculate time difference (procurement - referral)
merged_data['Time Difference'] = (merged_data['time_procured'] - merged_data['time_referred']).dt.total_seconds() / 3600  # Time difference in hours

# Group by 'Mechanism of Death' and calculate average time difference
avg_time_diff = merged_data.groupby('mechanism_of_death')['Time Difference'].mean().reset_index()

# Print the result
print(avg_time_diff)



           mechanism_of_death  Time Difference
0                Asphyxiation       110.935700
1                Blunt Injury       107.066895
2              Cardiovascular       100.448968
3   Death from Natural Causes        63.550680
4                    Drowning       116.006417
5           Drug Intoxication       104.320918
6                  Electrical       111.511563
7              Gun Shot Wound        95.280820
8               Gunshot Wound        72.290249
9              Natural Causes       106.429103
10          None of the Above       101.138974
11          None of the above        54.616667
12                      Other        56.929167
13                    Seizure       100.839926
14                       Stab        96.541678
15                     Stroke        86.378084
16        Sudden Infant Death        95.613979
17                    Unknown    -97002.425227


In [6]:
# 23 --How many referrals occurred in 2018?
import pandas as pd
referral_details = pd.read_excel('OrganDonor_Consolidated.xlsx', sheet_name='ReferralDetails')
referrals_2018 = referral_details[referral_details['Referral_Year'] == 2018].shape[0]
print(f"Number of referrals in 2018: {referrals_2018}")


Number of referrals in 2018: 19175


In [8]:
#29 How many deaths were registered with OPO 1? List them by year.
import pandas as pd

# Import data into pandas DataFrames (this can be CSV, Excel, etc.)
df_donardetails = pd.read_excel('OrganDonor_Consolidated.xlsx')
df_yearlyoutcomes = pd.read_excel('OrganDonor_Consolidated.xlsx', sheet_name='Yearly_Outcomes')
df_OPO1 =  df_yearlyoutcomes[df_yearlyoutcomes['OPO'] == 'OPO1']
print(df_OPO1)


     OPO  Year  mean calc deaths
30  OPO1  2015           2852.69
31  OPO1  2016           2954.13
32  OPO1  2017           3112.34
33  OPO1  2018           3019.04
34  OPO1  2019           3148.80
35  OPO1  2020           3236.50


In [7]:
#31 How many donors with a successful transplant died of a seizure?
import pandas as pd

# Import data into pandas DataFrames 
dataframe_donardetails = pd.read_excel('OrganDonor_Consolidated.xlsx')
dataframe_referraldetails = pd.read_excel('OrganDonor_Consolidated.xlsx', sheet_name='ReferralDetails')

# Merge data1 and data2 on a common column (e.g., 'donor_id')
merged_data = pd.merge(dataframe_donardetails, dataframe_referraldetails, on='PatientID', how='inner')

#Filter the merged DataFrame for successful transplants and cause of death 'Seizure'
successful_donors = merged_data[(merged_data['causeofdeath'] == 'Seizure') & (merged_data['transplanted'] == 1)]

# Count how many donors died of seizures after a successful transplant
num_donors_with_seizure = successful_donors.shape[0]

# Output the result
print(f"Number of donors with a successful transplant who died of a seizure: {num_donors_with_seizure}")



Number of donors with a successful transplant who died of a seizure: 3


In [19]:
import pandas as pd

try:
    # Load the Excel file into a DataFrame
    dataframe_ReferralDetails = pd.read_excel('OrganDonor_Consolidated.xlsx', sheet_name='ReferralDetails')

 
    # Convert timestamps to datetime, errors='coerce' to handle invalid datetime values
    dataframe_ReferralDetails['time_referred'] = pd.to_datetime(dataframe_ReferralDetails['time_referred'], errors='coerce')
    dataframe_ReferralDetails['time_procured'] = pd.to_datetime(dataframe_ReferralDetails['time_procured'], errors='coerce')

    # Count total referrals and procured referrals
    total_referrals = dataframe_ReferralDetails['time_referred'].notna().sum()  # Count total referrals
    procured_referrals = dataframe_ReferralDetails['time_procured'].notna().sum()  # Count procured referrals

    # Avoid division by zero if there are no referrals
    if total_referrals > 0:
        procured_percentage = (procured_referrals / total_referrals) * 100
        print(f"Percentage of referrals that are procured: {procured_percentage:.2f}%")
    else:
        print("No referrals found in the data.")

except Exception as e:
    print(f"An error occurred: {e}")


Percentage of referrals that are procured: 7.17%


In [20]:
pip list

Package                           Version
--------------------------------- ------------------
aiobotocore                       2.12.3
aiohappyeyeballs                  2.4.0
aiohttp                           3.10.5
aioitertools                      0.7.1
aiosignal                         1.2.0
alabaster                         0.7.16
altair                            5.0.1
anaconda-anon-usage               0.4.4
anaconda-catalogs                 0.2.0
anaconda-client                   1.12.3
anaconda-cloud-auth               0.5.1
anaconda-navigator                2.6.3
anaconda-project                  0.11.1
annotated-types                   0.6.0
anyio                             4.2.0
appdirs                           1.4.4
archspec                          0.2.3
argon2-cffi                       21.3.0
argon2-cffi-bindings              21.2.0
arrow                             1.2.3
astroid                           2.14.2
astropy                           6.1.3
astropy-iers-data