In [3]:
import numpy as np
import pandas as pd

In [5]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [8]:
#1.Using numpy functions, multiply the following arrays using matrix multiplication.
 #a=np.arange(4).reshape(2,2)
# b=np.arange(6).reshape(3,2)
a=np.arange(4).reshape(2,2)
b=np.arange(6).reshape(3,2)
b_trps=np.transpose(b)
print(a)
print(b_trps)
c=a @ b_trps
print(c)

[[0 1]
 [2 3]]
[[0 2 4]
 [1 3 5]]
[[ 1  3  5]
 [ 3 13 23]]


In [21]:
OrganD_df=pd.read_excel('OrganDonor_Consolidated.xlsx')


In [26]:
OrganD_df

PatientID   age gender      race              causeofdeath  \
0       OPO1_P155959  54.0      M     White                   Unknown   
1       OPO1_P297347  78.0      M  Hispanic                   Unknown   
2       OPO1_P399316  57.0      M  Hispanic                    Anoxia   
3       OPO1_P246407  78.0      F     Black  cerebrovascular accident   
4       OPO1_P187209  70.0      F     White                   Unknown   
...              ...   ...    ...       ...                       ...   
133096   OPO6_P54946  54.0      F     Black                    Anoxia   
133097  OPO6_P630991  63.0      M     Black  cerebrovascular accident   
133098    OPO6_P8748  28.0      M     White                    Anoxia   
133099    OPO6_P5461  85.0      F     White                    Anoxia   
133100  OPO6_P942291  32.0      M     Black                     Other   

       mechanism_of_death  brain_death       time_asystole time_brain_death  
0                 Unknown            0 2036-01-02 18:26:00              NaT  
1                 Unknown            0 2031-12-24 14:06:00              NaT  
2                 Unknown            0 2034-05-11 00:00:00              NaT  
3                  Stroke            0 2035-06-14 14:18:00              NaT  
4                 Unknown            0 2034-02-18 18:50:00              NaT  
...                   ...          ...                 ...              ...  
133096     Natural Causes            0 2032-09-16 02:34:00              NaT  
133097             Stroke            0 2034-06-06 22:14:00              NaT  
133098  Drug Intoxication            0                 NaT              NaT  
133099     Cardiovascular            0                 NaT              NaT  
133100     Natural Causes            0                 NaT              NaT  

[133101 rows x 9 columns]

In [22]:
DataD_df=pd.read_excel('DataDictionary.xlsx')

In [32]:
DataD_df

Field                                        Description  \
0                    OPO                                  Anonymized OPO ID   
1              PatientID                              Anonymized Patient ID   
2             HospitalID                 Referring hospital (anonymized ID)   
3                    Age                                  Exact patient age   
4                 Gender                                 Patient sex/gender   
5                   Race                                 Patient sex/gender   
6        Tissue_Referral     Was patient also referred for tissue donation?   
7           Eye_Referral     Was patient also referred for cornea donation?   
8           causeofdeath                                     Cause of death   
9     mechanism_of_death                    UNOS defined mechanism of death   
10           brain_death                   Was patient declared brain dead?   
11  Approached Relatives  Was patient's next-of-kin approached for donat...   
12  Authorized By Family  Did patient or their next-of-kin consent to do...   
13         Cross_Clamped   Was patient cross-clamped for organ procurement?   
14          transplanted        Did patients organ(s) lead to a transplant?   
15      time_brain_death                                Time of brain death   
16         time_asystole              Time of asystole (i.e. cardiac death)   
17         time_referred                     Time of referral from hospital   
18       time_approached                            Time of approach by OPO   
19       time_authorized  Time of consent given for donation by patient ...   
20         time_procured          Time of cross clamp for organ procurement   
21         Referral_Year                 Year in which patient was referred   
22    Referral_DayofWeek          Day of week on which patient was referred   
23         Procured_Year  Year in which patient was cross-clamped for pr...   
24         outcome_heart  Final disposition of procured heart (Transplan...   
25         outcome_liver  Final disposition of procured liver (Transplan...   
26   outcome_kidney_left  Final disposition of procured left kidney (Tra...   
27  outcome_kidney_right  Final disposition of procured right kidney (Tr...   
28     outcome_lung_left  Final disposition of procured left lung (Trans...   
29    outcome_lung_right  Final disposition of procured right lung (Tran...   
30     outcome_intestine  Final disposition of procured intestine (Trans...   
31      outcome_pancreas  Final disposition of procured pancreas (Transp...   

        Type                                              Notes  
0     String                                          e.g. OPO5  
1     String                               "e.g. ""OPO5_P123"""  
2     String                                "e.g. ""OPO5_H12"""  
3    Integer  If exact patient age was over 89, the age is l...  
4     String                                             M or F  
5     String  Five categories (Black/Af-Am, White/Caucasian,...  
6    Boolean  1- referred for tissue donation\n0-not referre...  
7    Boolean  1- referred for eye donation\n0-not referred f...  
8     String                               Categorical variable  
9     String     Categorical variable based on UNOS definitions  
10   Boolean  Brain death may not be documented if the OPO r...  
11   Boolean  0-patient's next-of-kin not approached for don...  
12   Boolean  1-patient or their next-of-kin consent to dona...  
13   Boolean  1 patient cross-clamped for organ procurement\...  
14   Boolean  1-patients organ(s) transplanted\n0- patients ...  
15  Datetime  Randomly date-shifted (all timestamps from the...  
16  Datetime  Randomly date-shifted (all timestamps from the...  
17  Datetime  Randomly date-shifted (all timestamps from the...  
18  Datetime  Randomly date-shifted (all timestamps from the...  
19  Datetime  Randomly date-shifted (all timestamps from the...  
20  Datetime  Randomly da

In [61]:
#2.On Average, what is the time that passes between approach and procurement?
sub_OrganD_df=OrganD_df[['time_approached','time_procured']]


KeyError: "None of [Index(['time_approached', 'time_procured'], dtype='object')] are in the [columns]"

In [9]:
df_donor_details=pd.read_excel('OrganDonor_Consolidated.xlsx',sheet_name='DonorDetails')
df_donor_details

PatientID   age gender      race              causeofdeath  \
0       OPO1_P155959  54.0      M     White                   Unknown   
1       OPO1_P297347  78.0      M  Hispanic                   Unknown   
2       OPO1_P399316  57.0      M  Hispanic                    Anoxia   
3       OPO1_P246407  78.0      F     Black  cerebrovascular accident   
4       OPO1_P187209  70.0      F     White                   Unknown   
...              ...   ...    ...       ...                       ...   
133096   OPO6_P54946  54.0      F     Black                    Anoxia   
133097  OPO6_P630991  63.0      M     Black  cerebrovascular accident   
133098    OPO6_P8748  28.0      M     White                    Anoxia   
133099    OPO6_P5461  85.0      F     White                    Anoxia   
133100  OPO6_P942291  32.0      M     Black                     Other   

       mechanism_of_death  brain_death       time_asystole time_brain_death  
0                 Unknown            0 2036-01-02 18:26:00              NaT  
1                 Unknown            0 2031-12-24 14:06:00              NaT  
2                 Unknown            0 2034-05-11 00:00:00              NaT  
3                  Stroke            0 2035-06-14 14:18:00              NaT  
4                 Unknown            0 2034-02-18 18:50:00              NaT  
...                   ...          ...                 ...              ...  
133096     Natural Causes            0 2032-09-16 02:34:00              NaT  
133097             Stroke            0 2034-06-06 22:14:00              NaT  
133098  Drug Intoxication            0                 NaT              NaT  
133099     Cardiovascular            0                 NaT              NaT  
133100     Natural Causes            0                 NaT              NaT  

[133101 rows x 9 columns]

In [19]:
#7.Make Patient ID as index to the table.


subdf_donor_details=df_donor_details['PatientID']
column_name=['age','gender','race','causeofdeath','mechanism_of_death','brain_death','time_asystole','time_brain_death']
subdf_donor_details
s1=pd.DataFrame(data=df_donor_details,index=subdf_donor_details,columns=column_name)
s1

age gender race causeofdeath mechanism_of_death  brain_death  \
PatientID                                                                    
OPO1_P155959  NaN    NaN  NaN          NaN                NaN          NaN   
OPO1_P297347  NaN    NaN  NaN          NaN                NaN          NaN   
OPO1_P399316  NaN    NaN  NaN          NaN                NaN          NaN   
OPO1_P246407  NaN    NaN  NaN          NaN                NaN          NaN   
OPO1_P187209  NaN    NaN  NaN          NaN                NaN          NaN   
...           ...    ...  ...          ...                ...          ...   
OPO6_P54946   NaN    NaN  NaN          NaN                NaN          NaN   
OPO6_P630991  NaN    NaN  NaN          NaN                NaN          NaN   
OPO6_P8748    NaN    NaN  NaN          NaN                NaN          NaN   
OPO6_P5461    NaN    NaN  NaN          NaN                NaN          NaN   
OPO6_P942291  NaN    NaN  NaN          NaN                NaN          NaN   

             time_asystole time_brain_death  
PatientID                                    
OPO1_P155959           NaT              NaT  
OPO1_P297347           NaT              NaT  
OPO1_P399316           NaT              NaT  
OPO1_P246407           NaT              NaT  
OPO1_P187209           NaT              NaT  
...                    ...              ...  
OPO6_P54946            NaT              NaT  
OPO6_P630991           NaT              NaT  
OPO6_P8748             NaT              NaT  
OPO6_P5461             NaT              NaT  
OPO6_P942291           NaT              NaT  

[133101 rows x 8 columns]

In [51]:
#8.Create a dictionary with the Age and Cause of Death for any 5 random donors.
 #Access any one cause of death using the donors age using the get() function
dic={
    "PatientID":['OPO1_P155959','OPO1_P297347','OPO1_P399316','OPO1_P246407','OPO1_P187209'],
    "age":[54,78,57,78,70],
    "causeofdeath":['Unknown','Unknown','Anoxia','cerebrovascular accident','Unknown']
}
print(dic)


{'PatientID': ['OPO1_P155959', 'OPO1_P297347', 'OPO1_P399316', 'OPO1_P246407', 'OPO1_P187209'], 'age': [54, 78, 57, 78, 70], 'causeofdeath': ['Unknown', 'Unknown', 'Anoxia', 'cerebrovascular accident', 'Unknown']}


In [59]:
#8.Access any one cause of death using the donors age using the get() function

age=dic['age']
causeofdeath=dic['causeofdeath']
data=dict(zip(age,causeofdeath))
#data
print(data.get(78))

cerebrovascular accident
