In [2]:
import numpy as np
import pandas as pd

In [3]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [3]:
#1.Using numpy functions, multiply the following arrays using matrix multiplication.
 #a=np.arange(4).reshape(2,2)
# b=np.arange(6).reshape(3,2)
a=np.arange(4).reshape(2,2)
b=np.arange(6).reshape(3,2)
b_trps=np.transpose(b)
print(a)
print(b_trps)
c=a @ b_trps
print(c)

[[0 1]
 [2 3]]
[[0 2 4]
 [1 3 5]]
[[ 1  3  5]
 [ 3 13 23]]


In [4]:
OrganD_df=pd.read_excel('OrganDonor_Consolidated.xlsx')


In [5]:
OrganD_df

PatientID   age gender      race              causeofdeath  \
0       OPO1_P155959  54.0      M     White                   Unknown   
1       OPO1_P297347  78.0      M  Hispanic                   Unknown   
2       OPO1_P399316  57.0      M  Hispanic                    Anoxia   
3       OPO1_P246407  78.0      F     Black  cerebrovascular accident   
4       OPO1_P187209  70.0      F     White                   Unknown   
...              ...   ...    ...       ...                       ...   
133096   OPO6_P54946  54.0      F     Black                    Anoxia   
133097  OPO6_P630991  63.0      M     Black  cerebrovascular accident   
133098    OPO6_P8748  28.0      M     White                    Anoxia   
133099    OPO6_P5461  85.0      F     White                    Anoxia   
133100  OPO6_P942291  32.0      M     Black                     Other   

       mechanism_of_death  brain_death       time_asystole time_brain_death  
0                 Unknown            0 2036-01-02 18:26:00              NaT  
1                 Unknown            0 2031-12-24 14:06:00              NaT  
2                 Unknown            0 2034-05-11 00:00:00              NaT  
3                  Stroke            0 2035-06-14 14:18:00              NaT  
4                 Unknown            0 2034-02-18 18:50:00              NaT  
...                   ...          ...                 ...              ...  
133096     Natural Causes            0 2032-09-16 02:34:00              NaT  
133097             Stroke            0 2034-06-06 22:14:00              NaT  
133098  Drug Intoxication            0                 NaT              NaT  
133099     Cardiovascular            0                 NaT              NaT  
133100     Natural Causes            0                 NaT              NaT  

[133101 rows x 9 columns]

In [6]:
DataD_df=pd.read_excel('DataDictionary.xlsx')

In [7]:
DataD_df

Field                                        Description  \
0                    OPO                                  Anonymized OPO ID   
1              PatientID                              Anonymized Patient ID   
2             HospitalID                 Referring hospital (anonymized ID)   
3                    Age                                  Exact patient age   
4                 Gender                                 Patient sex/gender   
5                   Race                                 Patient sex/gender   
6        Tissue_Referral     Was patient also referred for tissue donation?   
7           Eye_Referral     Was patient also referred for cornea donation?   
8           causeofdeath                                     Cause of death   
9     mechanism_of_death                    UNOS defined mechanism of death   
10           brain_death                   Was patient declared brain dead?   
11  Approached Relatives  Was patient's next-of-kin approached for donat...   
12  Authorized By Family  Did patient or their next-of-kin consent to do...   
13         Cross_Clamped   Was patient cross-clamped for organ procurement?   
14          transplanted        Did patients organ(s) lead to a transplant?   
15      time_brain_death                                Time of brain death   
16         time_asystole              Time of asystole (i.e. cardiac death)   
17         time_referred                     Time of referral from hospital   
18       time_approached                            Time of approach by OPO   
19       time_authorized  Time of consent given for donation by patient ...   
20         time_procured          Time of cross clamp for organ procurement   
21         Referral_Year                 Year in which patient was referred   
22    Referral_DayofWeek          Day of week on which patient was referred   
23         Procured_Year  Year in which patient was cross-clamped for pr...   
24         outcome_heart  Final disposition of procured heart (Transplan...   
25         outcome_liver  Final disposition of procured liver (Transplan...   
26   outcome_kidney_left  Final disposition of procured left kidney (Tra...   
27  outcome_kidney_right  Final disposition of procured right kidney (Tr...   
28     outcome_lung_left  Final disposition of procured left lung (Trans...   
29    outcome_lung_right  Final disposition of procured right lung (Tran...   
30     outcome_intestine  Final disposition of procured intestine (Trans...   
31      outcome_pancreas  Final disposition of procured pancreas (Transp...   

        Type                                              Notes  
0     String                                          e.g. OPO5  
1     String                               "e.g. ""OPO5_P123"""  
2     String                                "e.g. ""OPO5_H12"""  
3    Integer  If exact patient age was over 89, the age is l...  
4     String                                             M or F  
5     String  Five categories (Black/Af-Am, White/Caucasian,...  
6    Boolean  1- referred for tissue donation\n0-not referre...  
7    Boolean  1- referred for eye donation\n0-not referred f...  
8     String                               Categorical variable  
9     String     Categorical variable based on UNOS definitions  
10   Boolean  Brain death may not be documented if the OPO r...  
11   Boolean  0-patient's next-of-kin not approached for don...  
12   Boolean  1-patient or their next-of-kin consent to dona...  
13   Boolean  1 patient cross-clamped for organ procurement\...  
14   Boolean  1-patients organ(s) transplanted\n0- patients ...  
15  Datetime  Randomly date-shifted (all timestamps from the...  
16  Datetime  Randomly date-shifted (all timestamps from the...  
17  Datetime  Randomly date-shifted (all timestamps from the...  
18  Datetime  Randomly date-shifted (all timestamps from the...  
19  Datetime  Randomly date-shifted (all timestamps from the...  
20  Datetime  Randomly da

In [8]:
#2.On Average, what is the time that passes between approach and procurement?
sub_OrganD_df=OrganD_df[['time_approached','time_procured']]


KeyError: "None of [Index(['time_approached', 'time_procured'], dtype='object')] are in the [columns]"

In [ ]:
df_donor_details=pd.read_excel('OrganDonor_Consolidated.xlsx',sheet_name='DonorDetails')
df_donor_details

In [ ]:
#7.Make Patient ID as index to the table.


subdf_donor_details=df_donor_details['PatientID']
column_name=['age','gender','race','causeofdeath','mechanism_of_death','brain_death','time_asystole','time_brain_death']
subdf_donor_details
s1=pd.DataFrame(data=df_donor_details,index=subdf_donor_details,columns=column_name)
s1

In [ ]:
#8.Create a dictionary with the Age and Cause of Death for any 5 random donors.
 #Access any one cause of death using the donors age using the get() function
dic={
    "PatientID":['OPO1_P155959','OPO1_P297347','OPO1_P399316','OPO1_P246407','OPO1_P187209'],
    "age":[54,78,57,78,70],
    "causeofdeath":['Unknown','Unknown','Anoxia','cerebrovascular accident','Unknown']
}
print(dic)


In [ ]:
#8.Access any one cause of death using the donors age using the get() function

age=dic['age']
causeofdeath=dic['causeofdeath']
data=dict(zip(age,causeofdeath))
#data
print(data.get(78))

In [25]:
#Question 33.Which year had the maximum referrals
dfs = pd.read_excel('OrganDonor_Consolidated.xlsx',sheet_name = 'ReferralDetails' )
yearwise_count = dfs['Referral_Year'].value_counts()
maxcount_year = yearwise_count.idxmax()
print(f"The Year with maximum referrals is {maxcount_year}")

The Year with maximum referrals is 2021


In [4]:
#Question 34 How Many Organs are recovered for transplant but not transplanted?
dfs1 = pd.read_excel('OrganDonor_Consolidated.xlsx',sheet_name = 'Outcomes' )
valuetobe_counted = 'Recovered for Transplant but not Transplanted'
column_names  = dfs1.columns #['outcome_heart','outcome_liver','outcome_kidney_left','outcome_kidney_right','outcome_lung_left','outcome_lung_right','outcome_intestine','outcome_pancreas']
count = 0
for column_name in column_names:
    count  += dfs1[column_name].value_counts().get(valuetobe_counted,0)
    
print(count)

3245


In [31]:
#Question 35 . What are the 3 most frequenst causes of death?
dfs2 = pd.read_excel('OrganDonor_Consolidated.xlsx',sheet_name = 'DonorDetails' )
cause_death = dfs2['causeofdeath'].value_counts()
most_frequent = cause_death.head(3)

key_cause = ' , '.join(most_frequent.keys())
print(f"The 3 most frequent causes of death are {key_cause}")

The 3 most frequent causes of death are Anoxia , Unknown , cerebrovascular accident


In [3]:
#Question 36.How many transplants were registered under each OPO?
dfs3 = pd.read_excel('OrganDonor_Consolidated.xlsx',sheet_name = 'OPO_HospDetails' )
transplants_eachopo = dfs3['OPO'].value_counts()
print(transplants_eachopo)

OPO4    33641
OPO1    32148
OPO6    22915
OPO2    16145
OPO5    15738
OPO3    12514
Name: OPO, dtype: int64


In [ ]:
#Quuestion 37.Plot a stacked bar chart to show different procurement outcomes for organs - heart, liver, and pancreas.
 #Label the bars with the actual numbers for each outcome.
    

In [6]:
#Question 38.What percentage of all transplants are lung transplants
dfs1 = pd.read_excel('OrganDonor_Consolidated.xlsx',sheet_name = 'Outcomes' )
count_patients = len(dfs1)

valuetobe_counted = 'Transplanted'


count_left = dfs1['outcome_lung_left'].value_counts()
count_left_transplanted = count_left.get(valuetobe_counted, 0)


count_right = dfs1['outcome_lung_right'].value_counts()
count_right_transplanted = count_right.get(valuetobe_counted, 0)


# percentage of left lung transplants
percentage_left_lung = (count_left_transplanted/count_patients)*100
percentage_right_lung = (count_right_transplanted/count_patients)*100
print(f"Percentage of left lung transplants is : {percentage_left_lung:.2f}%")
print(f"Percentage of right lung transplants is: {percentage_right_lung:.2f}%")

Percentage of left lung transplants is : 22.51%
Percentage of right lung transplants is: 22.31%


In [9]:
#Question 39.Which year had the maximum number of procurements?
dfs = pd.read_excel('OrganDonor_Consolidated.xlsx',sheet_name = 'ReferralDetails' )
date_column = 'time_procured' 
dfs[date_column] = pd.to_datetime(dfs[date_column])
dfs['year'] = dfs[date_column].dt.year
year_count = dfs['year'].value_counts()
max_year = year_count.idxmax()
max_count = year_count.max()
print(f"The year with the maximum procurements is {int(max_year)} with {max_count} procurements.")

The year with the maximum procurements is 2035 with 1619 procurements.


In [11]:
#Question 40.Create a dataframe with date and time as columns, where the values are the referral time.
dfs = pd.read_excel('OrganDonor_Consolidated.xlsx',sheet_name = 'ReferralDetails' )
datestamp_column = 'time_referred'
dfs[datestamp_column] = pd.to_datetime(dfs[datestamp_column], errors='coerce')
dfs['PID'] = dfs['PatientID']
dfs['Date'] = dfs[datestamp_column].dt.strftime('%m/%d/%Y')
dfs['Referral Time'] = dfs[datestamp_column].dt.strftime('%I:%M %p')
print(dfs[['PID','Date','Referral Time']])

                 PID        Date Referral Time
0       OPO1_P320866  06/21/2033      06:49 AM
1       OPO1_P549364  11/21/2036      08:41 AM
2       OPO1_P536997  08/23/2030      11:28 PM
3       OPO1_P463285  05/12/2034      05:34 PM
4       OPO1_P284978  02/22/2033      04:45 AM
...              ...         ...           ...
133096  OPO6_P384794  07/10/2034      01:26 PM
133097  OPO6_P902138  08/04/2035      05:13 AM
133098    OPO6_P5461  03/13/2031      08:13 PM
133099  OPO6_P942291  11/20/2032      01:32 PM
133100  OPO6_P210235  02/26/2030      05:22 AM

[133101 rows x 3 columns]


In [ ]:
#Question 41.Create a pair plot of the outcomes, using different outcome statuses as the hue.

In [14]:
#Question 42.What is the ratio of referrals to transplants by year?
yearly_counts = dfs['Referral_Year'].value_counts()
count_transplanted =dfs[dfs['transplanted'] == 1].groupby('Referral_Year').size()
ratio = yearly_counts / count_transplanted
print(ratio.round(2))

2015    13.19
2016    12.63
2017    13.26
2018    15.06
2019    13.45
2020    16.36
2021    18.22
dtype: float64


In [15]:
#Question 43.How many donors died from a drug overdose?
dfs2 = pd.read_excel('OrganDonor_Consolidated.xlsx',sheet_name = 'DonorDetails' )
cause_death = dfs2['causeofdeath'].value_counts()
count_DrugOverdose = cause_death.get('Drug Overdose',0)
print(f"Number of Donors died from Drug Overdose are : {count_DrugOverdose}")

Number of Donors died from Drug Overdose are : 156


In [ ]:
#Question 44.Create a count plot to show distribution of patient-ages in any 2 mechanisms of death.

In [ ]:
#Question 45.Create a Waffle chart to show what percentage of total deaths belong to each mechanism

In [16]:
#Question 46.How many donors were registered under each hospital?
dfs3 = pd.read_excel('OrganDonor_Consolidated.xlsx',sheet_name = 'OPO_HospDetails' )
donors_eachhosp = dfs3['HospitalID'].value_counts()
print(donors_eachhosp)

OPO4_H16532    3682
OPO6_H22175    3629
OPO6_H6602     3578
OPO3_H4291     3123
OPO4_H30877    2335
               ... 
OPO5_H11845       1
OPO2_H6517        1
OPO2_H5905        1
OPO2_H158         1
OPO6_H21263       1
Name: HospitalID, Length: 557, dtype: int64


In [ ]:
#Question 47.What is the predominant 'identified mechanism of death' among the youngest donors in the dataset.
dfs2 = pd.read_excel('OrganDonor_Consolidated.xlsx',sheet_name = 'DonorDetails' )
youngest_donor_age = dfs2['age'].min()
youngest_donors = dfs2[dfs2['age']== youngest_donor_age]
mech_of_death = youngest_donors['causeofdeath'].value_counts()
max_mech_of_death = mech_of_death.idxmax()
print(f" The predominant mechanism of death among the youngest donors who is of age {int(youngest_donor_age)} is {max_mech_of_death}")

In [ ]:
#Question 48.Show a bar plot of the number of patients by race?